from dataclasses import replace

import pytest

from app.training.age import HattrickAge
from app.training.eligibility import TrainingExposure
from app.training.engine import TrainingRequest, calculate_training
from app.training.types import CoachLevel, Skill, TrainingType


def base_request(**overrides: object) -> TrainingRequest:
    values: dict[str, object] = {
        "age": HattrickAge(17, 0),
        "current_skill": 7.25,
        "training_type": TrainingType.PLAYMAKING,
        "target_skill": Skill.PLAYMAKING,
        "coach_level": CoachLevel.SOLID,
        "assistant_total_levels": 10,
        "intensity": 100,
        "stamina_share": 10,
        "exposure": TrainingExposure(full_minutes=90),
    }
    values.update(overrides)
    return TrainingRequest(**values)  # type: ignore[arg-type]


def test_fractional_skill_progression_returns_ui_ready_result() -> None:
    result = calculate_training(base_request(current_skill=8.43))

    assert result.skill_before == 8.43
    assert result.skill_after == pytest.approx(8.43 + result.skill_gain)
    assert result.visible_skill_before == 8
    assert result.visible_skill_after == 8
    assert result.skill_up is False


def test_skill_up_crossing() -> None:
    result = calculate_training(base_request(current_skill=8.85))

    assert result.visible_skill_before == 8
    assert result.visible_skill_after == 9
    assert result.skill_up is True


def test_minute_proportionality_in_engine() -> None:
    full = calculate_training(base_request())
    half = calculate_training(
        base_request(exposure=TrainingExposure(full_minutes=45))
    )
    assert half.skill_gain == pytest.approx(full.skill_gain / 2)


def test_training_type_must_train_requested_skill() -> None:
    with pytest.raises(ValueError, match="does not train"):
        calculate_training(base_request(target_skill=Skill.SCORING))


@pytest.mark.parametrize("bad_skill", [-0.1, 20.0, float("nan")])
def test_invalid_fractional_skill(bad_skill: float) -> None:
    with pytest.raises(ValueError, match="Fractional skill"):
        base_request(current_skill=bad_skill)


# Golden outputs are hand-evaluated from HO WeeklyTrainingType.java at commit
# 31622ccd42e104e21a853122ffd269bd9e98dc88, not generated by this engine.
@pytest.mark.parametrize(
    ("training_request", "expected_gain"),
    [
        (base_request(current_skill=7.25), 0.2502749659204538),
        (
            base_request(
                age=HattrickAge(19, 7),
                current_skill=9.2,
                training_type=TrainingType.WINGER,
                target_skill=Skill.WINGER,
                coach_level=CoachLevel.PASSABLE,
                assistant_total_levels=8,
                intensity=90,
                stamina_share=15,
                exposure=TrainingExposure(partial_minutes=90),
            ),
            0.09667712102400002,
        ),
        (
            base_request(
                age=HattrickAge(18, 43),
                current_skill=8.4,
                coach_level=CoachLevel.EXCELLENT,
                assistant_total_levels=5,
                stamina_share=20,
                exposure=TrainingExposure(full_minutes=36, partial_minutes=90),
            ),
            0.12007668581577603,
        ),
        (
            base_request(
                current_skill=10.5,
                training_type=TrainingType.DEFENDING,
                target_skill=Skill.DEFENDING,
                exposure=TrainingExposure(osmosis_minutes=90),
            ),
            0.0235006272,
        ),
        (
            base_request(
                current_skill=12.1,
                training_type=TrainingType.SET_PIECES,
                target_skill=Skill.SET_PIECES,
                exposure=TrainingExposure(full_minutes=90, bonus_minutes=90),
            ),
            0.6961874062500002,
        ),
    ],
)
def test_hattrick_organizer_golden_cases(
    training_request: TrainingRequest, expected_gain: float
) -> None:
    assert calculate_training(training_request).skill_gain == pytest.approx(
        expected_gain, rel=1e-12, abs=1e-12
    )


def test_request_is_immutable_for_week_by_week_reuse() -> None:
    request = base_request()
    result = calculate_training(request)
    next_week = replace(request, current_skill=result.skill_after, age=request.age.advance_week())
    assert next_week.current_skill == result.skill_after
    assert next_week.age == HattrickAge(17, 7)
